name: Fetch $COCK Holders Every 10 Minutes
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Cron API
        run: curl -X GET "token-dashboard-ronin-sabong-saga.vercel.app/api/holders"
